In [1]:
import nltk.tokenize as tk
doc = "Are you curious about tokenization? " \
      "Let's see how it works! " \
      "We need to analyze a couple of sentences " \
      "with punctuations to see it in action."
print(doc)

Are you curious about tokenization? Let's see how it works! We need to analyze a couple of sentences with punctuations to see it in action.


In [3]:
#拆句子
sents = tk.sent_tokenize(doc)
sents

['Are you curious about tokenization?',
 "Let's see how it works!",
 'We need to analyze a couple of sentences with punctuations to see it in action.']

In [4]:
words=tk.word_tokenize(doc)
words

['Are',
 'you',
 'curious',
 'about',
 'tokenization',
 '?',
 'Let',
 "'s",
 'see',
 'how',
 'it',
 'works',
 '!',
 'We',
 'need',
 'to',
 'analyze',
 'a',
 'couple',
 'of',
 'sentences',
 'with',
 'punctuations',
 'to',
 'see',
 'it',
 'in',
 'action',
 '.']

In [8]:
words1=tk.WordPunctTokenizer().tokenize(doc)
words1

['Are',
 'you',
 'curious',
 'about',
 'tokenization',
 '?',
 'Let',
 "'",
 's',
 'see',
 'how',
 'it',
 'works',
 '!',
 'We',
 'need',
 'to',
 'analyze',
 'a',
 'couple',
 'of',
 'sentences',
 'with',
 'punctuations',
 'to',
 'see',
 'it',
 'in',
 'action',
 '.']

In [14]:
import sklearn.feature_extraction.text as ft
import numpy as np

In [11]:
#词袋模型
doc="This hotel is very bad. The toilet in this hotel smells bad. The environment of this hotel is very good."
sents=tk.sent_tokenize(doc)
cv=ft.CountVectorizer()
bow=cv.fit_transform(sents)
print(bow)

  (0, 0)	1
  (0, 11)	1
  (0, 5)	1
  (0, 3)	1
  (0, 9)	1
  (1, 7)	1
  (1, 4)	1
  (1, 10)	1
  (1, 8)	1
  (1, 0)	1
  (1, 3)	1
  (1, 9)	1
  (2, 2)	1
  (2, 6)	1
  (2, 1)	1
  (2, 8)	1
  (2, 11)	1
  (2, 5)	1
  (2, 3)	1
  (2, 9)	1


In [12]:
print(bow.toarray())
print(cv.get_feature_names())

[[1 0 0 1 0 1 0 0 0 1 0 1]
 [1 0 0 1 1 0 0 1 1 1 1 0]
 [0 1 1 1 0 1 1 0 1 1 0 1]]
['bad', 'environment', 'good', 'hotel', 'in', 'is', 'of', 'smells', 'the', 'this', 'toilet', 'very']


In [16]:
#TFIDF
tt=ft.TfidfTransformer()
tfidf = tt.fit_transform(bow)
print(np.round(tfidf.toarray(),3))

[[0.488 0.    0.    0.379 0.    0.488 0.    0.    0.    0.379 0.    0.488]
 [0.345 0.    0.    0.268 0.454 0.    0.    0.454 0.345 0.268 0.454 0.   ]
 [0.    0.429 0.429 0.253 0.    0.326 0.429 0.    0.326 0.253 0.    0.326]]
