In [1]:
import pandas as pd
import numpy as np

In [3]:
#加载数据
ratings = pd.read_json('ratings.json')
ratings

John Carson  Michelle Peterson  William Reynolds  \
Inception                 2.5                3.0               2.5   
Pulp Fiction              3.5                3.5               3.0   
Anger Management          3.0                1.5               NaN   
Fracture                  3.5                5.0               3.5   
Serendipity               2.5                3.5               NaN   
Jerry Maguire             3.0                3.0               4.0   

                  Jillian Hobart  Melissa Jones  Alex Roberts  Michael Henry  
Inception                    NaN              3           3.0            NaN  
Pulp Fiction                 3.5              4           4.0            4.5  
Anger Management             3.0              2           NaN            NaN  
Fracture                     4.0              3           5.0            4.0  
Serendipity                  2.5              2           3.5            1.0  
Jerry Maguire                4.5              3           3.0            NaN

In [5]:
fracture = ratings.loc['Fracture']
np.mean(fracture)
fracture.mean()

4.0

In [6]:
ratings.mean(axis=0)

John Carson          3.000000
Michelle Peterson    3.250000
William Reynolds     3.250000
Jillian Hobart       3.500000
Melissa Jones        2.833333
Alex Roberts         3.700000
Michael Henry        3.166667
dtype: float64

In [7]:
ratings.mean(axis=1)

Inception           2.800000
Pulp Fiction        3.714286
Anger Management    2.375000
Fracture            4.000000
Serendipity         2.500000
Jerry Maguire       3.416667
dtype: float64

In [8]:
fracture

John Carson          3.5
Michelle Peterson    5.0
William Reynolds     3.5
Jillian Hobart       4.0
Melissa Jones        3.0
Alex Roberts         5.0
Michael Henry        4.0
Name: Fracture, dtype: float64

In [9]:
np.average(fracture,weights=[2,3,3,1,1,1,1])

4.041666666666667

In [11]:
ratings.max()

John Carson          3.5
Michelle Peterson    5.0
William Reynolds     4.0
Jillian Hobart       4.5
Melissa Jones        4.0
Alex Roberts         5.0
Michael Henry        4.5
dtype: float64

In [10]:
ratings

John Carson  Michelle Peterson  William Reynolds  \
Inception                 2.5                3.0               2.5   
Pulp Fiction              3.5                3.5               3.0   
Anger Management          3.0                1.5               NaN   
Fracture                  3.5                5.0               3.5   
Serendipity               2.5                3.5               NaN   
Jerry Maguire             3.0                3.0               4.0   

                  Jillian Hobart  Melissa Jones  Alex Roberts  Michael Henry  
Inception                    NaN              3           3.0            NaN  
Pulp Fiction                 3.5              4           4.0            4.5  
Anger Management             3.0              2           NaN            NaN  
Fracture                     4.0              3           5.0            4.0  
Serendipity                  2.5              2           3.5            1.0  
Jerry Maguire                4.5              3           3.0            NaN

In [13]:
a= np.arange(1,10)
b=a[::-1]
print(np.maximum(a,b))
print(np.minimum(a,b))

[9 8 7 6 5 6 7 8 9]
[1 2 3 4 5 4 3 2 1]


In [14]:
fracture

John Carson          3.5
Michelle Peterson    5.0
William Reynolds     3.5
Jillian Hobart       4.0
Melissa Jones        3.0
Alex Roberts         5.0
Michael Henry        4.0
Name: Fracture, dtype: float64

In [15]:
fracture.median()

4.0

In [16]:
ratings.median(axis=1)

Inception           3.0
Pulp Fiction        3.5
Anger Management    2.5
Fracture            4.0
Serendipity         2.5
Jerry Maguire       3.0
dtype: float64

In [55]:
data = pd.read_excel('CustomerSurvival.xlsx')
data

ID  套餐金额       额外通话时长        额外流量  改变行为  服务合约  关联购买  集团用户  使用月数  流失用户
0        1     1   792.833333  -10.450067     0     0     0     0    25     0
1        2     1   121.666667  -21.141117     0     0     0     0    25     0
2        3     1   -30.000000  -25.655273     0     0     0     0     2     1
3        4     1   241.500000 -288.341254     0     1     0     1    25     0
4        5     1  1629.666667  -23.655505     0     0     0     1    25     0
...    ...   ...          ...         ...   ...   ...   ...   ...   ...   ...
4970  4971     1  1109.333333   49.843215     0     1     0     1    25     0
4971  4972     1   197.833333  -34.987142     0     1     0     0    21     1
4972  4973     1   162.833333   71.369162     0     1     0     0    25     0
4973  4974     1   358.166667   26.315733     0     1     0     0    21     1
4974  4975     3  -655.666667  -96.435175     0     1     0     1    25     0

[4975 rows x 10 columns]

In [25]:
print(data['流失用户'].value_counts())
print(data['流失用户'].mode())

1    3894
0    1081
Name: 流失用户, dtype: int64
0    1
dtype: int64


In [28]:
print(data['套餐金额'].value_counts())
print(data['套餐金额'].mode())

1    4719
2     225
3      31
Name: 套餐金额, dtype: int64
0    1
dtype: int64


In [31]:
data['额外通话时长'].quantile([0,0.25,0.5,0.75,1])

0.00   -2828.333333
0.25    -126.666667
0.50      13.500000
0.75     338.658333
1.00    4314.000000
Name: 额外通话时长, dtype: float64

In [32]:
data['额外流量'].quantile([0,0.25,0.5,0.75,1])

0.00   -2189.875986
0.25     -74.289824
0.50     -59.652734
0.75     -25.795045
1.00    2568.704293
Name: 额外流量, dtype: float64

In [33]:
ratings.std(axis=0)

John Carson          0.447214
Michelle Peterson    1.129159
William Reynolds     0.645497
Jillian Hobart       0.790569
Melissa Jones        0.752773
Alex Roberts         0.836660
Michael Henry        1.892969
dtype: float64

In [34]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Inception to Jerry Maguire
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   John Carson        6 non-null      float64
 1   Michelle Peterson  6 non-null      float64
 2   William Reynolds   4 non-null      float64
 3   Jillian Hobart     5 non-null      float64
 4   Melissa Jones      6 non-null      int64  
 5   Alex Roberts       5 non-null      float64
 6   Michael Henry      3 non-null      float64
dtypes: float64(6), int64(1)
memory usage: 544.0+ bytes


In [35]:
ratings.describe()

John Carson  Michelle Peterson  William Reynolds  Jillian Hobart  \
count     6.000000           6.000000          4.000000        5.000000   
mean      3.000000           3.250000          3.250000        3.500000   
std       0.447214           1.129159          0.645497        0.790569   
min       2.500000           1.500000          2.500000        2.500000   
25%       2.625000           3.000000          2.875000        3.000000   
50%       3.000000           3.250000          3.250000        3.500000   
75%       3.375000           3.500000          3.625000        4.000000   
max       3.500000           5.000000          4.000000        4.500000   

       Melissa Jones  Alex Roberts  Michael Henry  
count       6.000000       5.00000       3.000000  
mean        2.833333       3.70000       3.166667  
std         0.752773       0.83666       1.892969  
min         2.000000       3.00000       1.000000  
25%         2.250000       3.00000       2.500000  
50%         3.000000       3.50000       4.000000  
75%         3.000000       4.00000       4.250000  
max         4.000000       5.00000       4.500000

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4975 entries, 0 to 4974
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   ID      4975 non-null   int64  
 1   套餐金额    4975 non-null   int64  
 2   额外通话时长  4975 non-null   float64
 3   额外流量    4975 non-null   float64
 4   改变行为    4975 non-null   int64  
 5   服务合约    4975 non-null   int64  
 6   关联购买    4975 non-null   int64  
 7   集团用户    4975 non-null   int64  
 8   使用月数    4975 non-null   int64  
 9   流失用户    4975 non-null   int64  
dtypes: float64(2), int64(8)
memory usage: 388.8 KB


In [37]:
data=pd.read_csv('./泰坦尼克号生存数据/train.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [38]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [42]:
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [43]:
ratings

John Carson  Michelle Peterson  William Reynolds  \
Inception                 2.5                3.0               2.5   
Pulp Fiction              3.5                3.5               3.0   
Anger Management          3.0                1.5               NaN   
Fracture                  3.5                5.0               3.5   
Serendipity               2.5                3.5               NaN   
Jerry Maguire             3.0                3.0               4.0   

                  Jillian Hobart  Melissa Jones  Alex Roberts  Michael Henry  
Inception                    NaN              3           3.0            NaN  
Pulp Fiction                 3.5              4           4.0            4.5  
Anger Management             3.0              2           NaN            NaN  
Fracture                     4.0              3           5.0            4.0  
Serendipity                  2.5              2           3.5            1.0  
Jerry Maguire                4.5              3           3.0            NaN

In [47]:
a= ratings['John Carson']
b=ratings['Michelle Peterson']
c=ratings['Melissa Jones']
#均值
ma = a.mean()
mb=b.mean()
mc=c.mean()
#离差
dev_a = a -ma
dev_b = b - mb
dev_c = c-mc
#协方差
cov_ab=np.mean(dev_a * dev_b)
cov_bc=np.mean(dev_b*dev_c)
print(cov_ab)
print(cov_bc)

0.16666666666666666
0.2916666666666667


In [48]:
#相关系数
coef_ab=cov_ab / (np.std(a) * np.std(b))
coef_bc=cov_bc /(np.std(b)*np.std(c))
print(coef_ab,coef_bc)

0.3960590171906697 0.4117647058823529


In [49]:
np.corrcoef(a,b)

array([[1.        , 0.39605902],
       [0.39605902, 1.        ]])

In [51]:
np.corrcoef((a,b,c))

array([[1.        , 0.39605902, 0.59408853],
       [0.39605902, 1.        , 0.41176471],
       [0.59408853, 0.41176471, 1.        ]])

In [52]:
ratings.corr()

John Carson  Michelle Peterson  William Reynolds  \
John Carson           1.000000           0.396059          0.404520   
Michelle Peterson     0.396059           1.000000          0.204598   
William Reynolds      0.404520           0.204598          1.000000   
Jillian Hobart        0.566947           0.314970          1.000000   
Melissa Jones         0.594089           0.411765         -0.258199   
Alex Roberts          0.747018           0.963796          0.134840   
Michael Henry         0.991241           0.381246         -1.000000   

                   Jillian Hobart  Melissa Jones  Alex Roberts  Michael Henry  
John Carson              0.566947       0.594089      0.747018       0.991241  
Michelle Peterson        0.314970       0.411765      0.963796       0.381246  
William Reynolds         1.000000      -0.258199      0.134840      -1.000000  
Jillian Hobart           1.000000       0.566947      0.028571       0.893405  
Melissa Jones            0.566947       1.000000      0.211289       0.924473  
Alex Roberts             0.028571       0.211289      1.000000       0.662849  
Michael Henry            0.893405       0.924473      0.662849       1.000000

In [53]:
np.cov(a,b)

array([[0.2  , 0.2  ],
       [0.2  , 1.275]])

In [56]:
data


ID  套餐金额       额外通话时长        额外流量  改变行为  服务合约  关联购买  集团用户  使用月数  流失用户
0        1     1   792.833333  -10.450067     0     0     0     0    25     0
1        2     1   121.666667  -21.141117     0     0     0     0    25     0
2        3     1   -30.000000  -25.655273     0     0     0     0     2     1
3        4     1   241.500000 -288.341254     0     1     0     1    25     0
4        5     1  1629.666667  -23.655505     0     0     0     1    25     0
...    ...   ...          ...         ...   ...   ...   ...   ...   ...   ...
4970  4971     1  1109.333333   49.843215     0     1     0     1    25     0
4971  4972     1   197.833333  -34.987142     0     1     0     0    21     1
4972  4973     1   162.833333   71.369162     0     1     0     0    25     0
4973  4974     1   358.166667   26.315733     0     1     0     0    21     1
4974  4975     3  -655.666667  -96.435175     0     1     0     1    25     0

[4975 rows x 10 columns]

In [57]:
np.corrcoef(data['额外通话时长'],data['额外流量'])

array([[1.        , 0.06908135],
       [0.06908135, 1.        ]])